# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a4f24d97dcf128b0750a31e9263d8d48a36055b79b0b45e61f6b7e5893e83dd300eb2a8bb55995b8385067bf6cd78eb6f33fcc2c92df9eb7d5620a062ba4789

test:
  secret_key_base: 6f8a152ac36ff2d276a2bf07b6fc2d58b1d5566f952ab8d98594e487854e2ec0f2d50c13a36ec8160bc54842a581d9ad7134265bf1f8a72f29357314b262e459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
